version: "3.7"

services:
  
  postgres:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./test_data:/test_data
    ports:
      - "127.0.0.1:5432:5432"

  speaky-bot:
    build:
      context: .
    image: speaky-django:latest
    environment:
      DJANGO_SECRET_KEY: "arfdgvds"
      DJ_DEBUG: "False"
      TG_TOKEN: ""
      
    depends_on:
      - postgres

    command:
      - sh
      - -c
      - |
        python manage.py async_bot

  speaky-admin:
    build:
      context: .
    image: speaky-django:latest
    env_file:
      - ./.env
    ports:
      - '8000'
    volumes:
      - ./nginx-templates:/app/nginx-templates
      - nginx_assets:/app/assets/
      - nginx_media:/var/www/media/
    environment:
      DJ_DEBUG: "True"
      
    depends_on:
      - postgres

    command:
      - sh
      - -c
      - |
        python manage.py collectstatic --noinput
        python manage.py runserver 0.0.0.0:8000 --noreload

  nginx:
    image: nginx
    ports:
      - 127.0.0.1:8000:80
    environment:
      UPSTREAM_SERVER: speaky-admin:8000
    volumes:
      - ./nginx-templates:/etc/nginx/templates/
      - nginx_assets:/var/www/static/
      - nginx_media:/var/www/media/
    depends_on:
      - speaky-admin



volumes:
  db_data:
  nginx_media:
  nginx_assets:
