version: "3.7"

services:
  speaky-bot:
    build:
      context: .
    image: speaky-django:latest
    ports:
      - 80:8000
    volumes:
      - database:/var/www/database
      - media:/var/www/media
    environment:
      DJANGO_SECRET_KEY: ""
      DJ_DEBUG: "False"
      ALLOWED_HOSTS: '127.0.0.1,localhost'
      TG_TOKEN: ""
      DB_PATH: '/var/www/database/db.sqlite3'
      MEDIA_ROOT: '/var/www/media'

    command:
      - sh
      - -c
      - |
        python manage.py collectstatic --noinput
        python manage.py async_bot & \
        python manage.py runserver 0.0.0.0:8000 --noreload --insecure

volumes:
  database:
  media:
