# Generated by Django 4.2.4 on 2023-09-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Разговорный клуб High Inter / Upper', 'Speak Club Upper'), ('Разговорный клуб Advanced', 'Speak Club Adv'), ('Индивидуальные занятия', 'Private Lessons'), ('Групповые занятия', 'Group Lessons')], max_length=128, unique=True, verbose_name='Что за ссылка?')),
                ('link', models.CharField(max_length=128, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(choices=[('speaky_club', 'Speaky Club'), ('group_lessons', 'Group Lessons'), ('personal_lessons', 'Personal Lessons')], max_length=50, unique=True, verbose_name='Название продукта для бота')),
                ('name', models.CharField(max_length=128, verbose_name='Название продукта для отображения')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=128, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
