# Generated by Django 4.2.4 on 2023-09-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wednesday_upper', models.BooleanField(default=True, verbose_name='Есть места в High inter/upper: среда 19:00')),
                ('thursday_upper', models.BooleanField(default=True, verbose_name='Есть места в High inter/upper: четверг 19:00')),
            ],
            options={
                'verbose_name': 'Есть места в группах?',
                'verbose_name_plural': 'Есть места в группах?',
            },
        ),
        migrations.AlterField(
            model_name='externallink',
            name='source',
            field=models.CharField(choices=[('Чат: Разговорный клуб High Inter / Upper (Среда 19:00).', 'Chat Speak Club Upper Wed'), ('Чат: Разговорный клуб High Inter / Upper (Четверг 19:00).', 'Chat Speak Club Upper Thur'), ('Форма: Групповые занятия', 'Form Group Lessons'), ('Форма: Индивидуальные занятия', 'Form Personal Lessons')], max_length=128, unique=True, verbose_name='Что за ссылка?'),
        ),
    ]
