# Generated by Django 4.2.4 on 2023-09-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_rub',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_usd',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='RUB', max_length=128, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
