# Generated by Django 4.2.4 on 2023-09-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_price_rub_remove_product_price_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Разговорный клуб High Inter / Upper', 'Speak Club Upper'), ('Разговорный клуб Advanced', 'Speak Club Adv'), ('Индивидуальные занятия', 'Private Lessons'), ('Групповые занятия', 'Group Lessons')], max_length=128, unique=True, verbose_name='Что за ссылка?')),
                ('link', models.CharField(max_length=128, verbose_name='Ссылка')),
            ],
        ),
    ]
