# Generated by Django 4.2.4 on 2023-09-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_externallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallink',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
