# Generated by Django 4.2.4 on 2023-09-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_externallink_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_name',
            field=models.CharField(default='user', max_length=50, unique=True, verbose_name='Название продукта для бота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название продукта для отображения'),
        ),
    ]
