# Generated by Django 4.2.4 on 2023-09-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_id_name_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_name',
            field=models.CharField(choices=[('speaky_club', 'Speaky Club'), ('group_lessons', 'Group Lessons'), ('personal_lessons', 'Personal Lessons')], max_length=50, unique=True, verbose_name='Название продукта для бота'),
        ),
    ]
