# Generated by Django 4.2.4 on 2023-09-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto_renew', models.BooleanField(default=False, verbose_name='Автоматически продлевать?')),
                ('sub_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала подписки')),
                ('unsub_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('verified_payment_id', models.UUIDField(blank=True, null=True, verbose_name='Подтвержденный ID платежа (автоматическое продление подписки)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='product.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='user.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
