# Generated by Django 4.2.4 on 2023-09-16 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_currency_alter_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_refunded',
            field=models.BooleanField(default=False, verbose_name='Возвращен?'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('succeeded', 'Succeeded')], default='created', max_length=128, verbose_name='Статус')),
                ('payment_service_id', models.UUIDField(verbose_name='Id возврата в платежной системе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='payment.payment', verbose_name='Возврат')),
            ],
        ),
    ]
