# Generated by Django 4.2.4 on 2023-09-06 08:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Текст шаблона'),
        ),
    ]
