# Generated by Django 4.2.4 on 2023-09-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_alter_template_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Текст шаблона'),
        ),
    ]
