# Generated by Django 4.2.4 on 2023-08-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_sub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата первой подписки'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_accepted_to_autopayment',
            field=models.BooleanField(default=False, verbose_name='Согласен на автоматические списания'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_payment_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Подтвержденный ID платежа (автоматическое продление подписки)'),
        ),
    ]
