# Generated by Django 4.2.4 on 2023-09-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_first_sub_date_user_is_accepted_to_autopayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего посещения'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='NEW', max_length=50, verbose_name='Статус переписки в боте'),
        ),
    ]
