# Generated by Django 4.2.4 on 2023-09-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_is_accepted_to_autopayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('role', models.CharField(blank=True, max_length=128, null=True, verbose_name='Роль')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='teacher_photos/', verbose_name='Фотография преподавателя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
